# Numpy套件

In [6]:
import numpy as op
b=op.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


# numpy 套件的ndarray型態,提供element-wise的操作

In [7]:
print(type(b))
print(b.ndim)#ndarray的維度
print(b.shape) #ndarray的shape
print(b.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [12]:
print(op.zeros(6))#產生6個元素均為0的一維array
print(op.zeros((3,6)))#產生18個元素均為0的二維array
print(op.zeros((2,3,6)))#產生36個元素均為0的三維array

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [9]:
a=op.zeros(16)
print(a)
print(a.shape)
b=a.reshape((4,4)) #改變資料的維度4X4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


In [10]:
my_array=op.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5]) #取0,1,2,3,4位置的值

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [11]:
a=op.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b=op.array([op.arange(0,5),op.arange(5,10)])
print(b)
c=op.array(op.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
import numpy as op
my_2d_array=op.array(op.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:])#第0列的元素
print(my_2d_array[1,])#第1列的元素
print(my_2d_array[:,0]) #第0欄的元素
print(my_2d_array[1,1])  #第2列第2欄的元素                   

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6


## 假設有六個組別"Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"
## 其參加人數分別為56, 8, 19, 14, 6, 71人

In [13]:
import numpy as np
groups=["Modem Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ir=[56,8,19,14,6,71]
groups_array=np.array(groups)
ir_array=np.array(ir)
print(groups_array)
print(ir_array)

['Modem Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


## 請問大於10人的組別有哪些?

In [14]:
#用人數去選組別
print(ir_array>=10)
print(groups_array[ir_array >=10])

[ True False  True  True False  True]
['Modem Web' 'Cloud' 'Big Data' '自我挑戰組']


## 除了自我挑戰組之外的組別,人數為何?

In [15]:
#用組別去篩選
print(groups_array!="自我挑戰組")
print(ir_array[groups_array!="自我挑戰組"])

[ True  True  True  True  True False]
[56  8 19 14  6]


## ndarray空值nan無限大inf

In [16]:
nan_array =np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


## 生成10組標準常態分配(平均為0,標準為1的常態分配)隨機變數


In [17]:
uniform_samples=np.random.uniform(size=10)
print(uniform_samples)

[0.99384132 0.5635263  0.72201347 0.70912521 0.80427039 0.16157027
 0.50764009 0.61429365 0.74049996 0.29603707]


## 生成10組介於0~1之間的隨機變數

In [18]:
uniform_samples = np.random.uniform(size=10)
print(uniform_samples)

[0.15595367 0.56015113 0.52354039 0.43424816 0.24856896 0.16291874
 0.83644837 0.02837485 0.78490947 0.32598598]
